-- Your SQL goes here

CREATE TABLE password(
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  username TEXT DEFAULT NULL,
  email TEXT DEFAULT NULL,
  pass TEXT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  kdf_salt TEXT DEFAULT NULL,
  aes_nonce TEXT DEFAULT NULL
);
